import type { Booking, BookingSlot } from "@/types/booking";
import { generateFixtures } from "@/lib/fixtures";
import type { Tournament } from "@/types/tournament";
import type { UserProfile } from "@/types/user";
import type { Venue } from "@/types/venue";

export const zones = [
  "Andheri",
  "Navi Mumbai",
  "Mumbai City",
  "Mumbai Suburban",
  "Thane",
] as const;

export const venues: Venue[] = [
  {
    id: "venue-1",
    name: "KickOff Arena Andheri West",
    zone: "Andheri",
    address: "Link Road, Andheri West, Mumbai",
    lat: 19.1375,
    lng: 72.8331,
    sports: [
      { sport: "football", pricePerHour: 700 },
      { sport: "cricket", pricePerHour: 600 },
    ],
    rating: 4.7,
    reviewCount: 42,
    amenities: ["parking", "floodlights", "changing-room", "cafeteria"],
    images: ["/images/venue-1-a.jpg", "/images/venue-1-b.jpg"],
    hours: "06:00 - 23:00",
    description: "High-quality astro turf with LED lighting and pro-grade drainage.",
    distanceKm: 2.3,
  },
  {
    id: "venue-2",
    name: "AstroTurf Arena Vashi",
    zone: "Navi Mumbai",
    address: "Sector 17, Vashi, Navi Mumbai",
    lat: 19.076,
    lng: 72.9986,
    sports: [
      { sport: "football", pricePerHour: 750 },
      { sport: "badminton", pricePerHour: 380 },
    ],
    rating: 4.8,
    reviewCount: 67,
    amenities: ["parking", "floodlights", "showers"],
    images: ["/images/venue-2-a.jpg", "/images/venue-2-b.jpg"],
    hours: "05:30 - 23:30",
    description: "Premium multi-sport facility with integrated booking and QR check-in.",
    distanceKm: 4.1,
  },
  {
    id: "venue-3",
    name: "Harbour Sports Club",
    zone: "Mumbai City",
    address: "Colaba Causeway, Mumbai",
    lat: 18.9067,
    lng: 72.8147,
    sports: [
      { sport: "tennis", pricePerHour: 950 },
      { sport: "swimming", pricePerHour: 500 },
      { sport: "basketball", pricePerHour: 550 },
    ],
    rating: 4.5,
    reviewCount: 31,
    amenities: ["parking", "cafeteria", "pro-shop"],
    images: ["/images/venue-3-a.jpg", "/images/venue-3-b.jpg"],
    hours: "06:00 - 22:00",
    description: "A long-standing sports club with refurbished courts and lap pool.",
    distanceKm: 6.8,
  },
  {
    id: "venue-4",
    name: "Suburban Smash Courts",
    zone: "Mumbai Suburban",
    address: "SV Road, Kandivali East, Mumbai",
    lat: 19.205,
    lng: 72.862,
    sports: [
      { sport: "badminton", pricePerHour: 350 },
      { sport: "cricket", pricePerHour: 500 },
    ],
    rating: 4.4,
    reviewCount: 24,
    amenities: ["parking", "changing-room"],
    images: ["/images/venue-4-a.jpg", "/images/venue-4-b.jpg"],
    hours: "07:00 - 22:30",
    description: "Budget-friendly indoor courts with strong local community leagues.",
    distanceKm: 3.6,
  },
  {
    id: "venue-5",
    name: "Thane Titans Sports Hub",
    zone: "Thane",
    address: "Ghodbunder Road, Thane West",
    lat: 19.2183,
    lng: 72.9781,
    sports: [
      { sport: "football", pricePerHour: 640 },
      { sport: "basketball", pricePerHour: 500 },
      { sport: "tennis", pricePerHour: 820 },
    ],
    rating: 4.6,
    reviewCount: 39,
    amenities: ["parking", "floodlights", "cafeteria", "medical-room"],
    images: ["/images/venue-5-a.jpg", "/images/venue-5-b.jpg"],
    hours: "06:00 - 00:00",
    description: "Tournament-ready complex with digital scoreboards and warm-up zone.",
    distanceKm: 8.2,
  },
];

export const sampleSlots: BookingSlot[] = [
  { time: "06:00", status: "available" },
  { time: "07:00", status: "available" },
  { time: "08:00", status: "booked" },
  { time: "09:00", status: "booked" },
  { time: "10:00", status: "pending" },
  { time: "11:00", status: "available" },
  { time: "12:00", status: "available" },
  { time: "13:00", status: "booked" },
  { time: "14:00", status: "available" },
  { time: "15:00", status: "available" },
  { time: "16:00", status: "pending" },
  { time: "17:00", status: "booked" },
  { time: "18:00", status: "available" },
  { time: "19:00", status: "available" },
  { time: "20:00", status: "booked" },
  { time: "21:00", status: "available" },
];

export const mockBookings: Booking[] = [
  {
    id: "SPT-20260405-4472",
    venueId: "venue-2",
    venueName: "AstroTurf Arena Vashi",
    sport: "football",
    date: "2026-04-12",
    startTime: "18:00",
    durationHours: 2,
    teamSize: 10,
    totalPrice: 1500,
    status: "confirmed",
  },
  {
    id: "SPT-20260406-9811",
    venueId: "venue-1",
    venueName: "KickOff Arena Andheri West",
    sport: "cricket",
    date: "2026-04-14",
    startTime: "20:00",
    durationHours: 1,
    teamSize: 8,
    totalPrice: 600,
    status: "pending",
  },
];

const registeredTeams = [
  "RedWolves",
  "Blue Eagles",
  "FC Navi",
  "City Kicks",
  "Andheri FC",
  "The Saints",
  "Goal Getters",
  "Phoenix FC",
];

export const tournaments: Tournament[] = [
  {
    id: "tour-1",
    name: "Andheri Premier Football League - Season 3",
    sport: "football",
    location: "Andheri",
    format: "round-robin",
    entryFee: 2000,
    maxTeams: 8,
    registeredTeams,
    startsAt: "2026-05-15",
    endsAt: "2026-06-10",
    venueId: "venue-1",
    prizePool: 100000,
    fixtures: generateFixtures(registeredTeams, "round-robin"),
  },
  {
    id: "tour-2",
    name: "Navi Mumbai Smash Cup",
    sport: "badminton",
    location: "Navi Mumbai",
    format: "knockout",
    entryFee: 1200,
    maxTeams: 16,
    registeredTeams: ["Smash Bros", "Birdie Hunters", "Net Ninjas", "Court Kings"],
    startsAt: "2026-05-05",
    endsAt: "2026-05-22",
    venueId: "venue-2",
    prizePool: 60000,
    fixtures: generateFixtures(
      ["Smash Bros", "Birdie Hunters", "Net Ninjas", "Court Kings"],
      "knockout",
    ),
  },
];

export const demoUser: UserProfile = {
  id: "user-1",
  name: "Aarav Patil",
  email: "aarav@sportspot.app",
  location: "Andheri",
  preferredSports: ["football", "badminton"],
  skillLevel: "intermediate",
  stats: {
    hoursPlayed: 123,
    courtsVisited: 19,
    tournamentsWon: 4,
  },
};
