CREATE DATABASE SEB234_STMS;

USE SEB234_STMS;

CREATE TABLE TEAM (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PLAYER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  team_id INT,
  FOREIGN KEY (team_id) REFERENCES TEAM(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TOURNAMENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  start_date DATE,
  end_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MATCHES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tournament_id INT,
  team1_id INT,
  team2_id INT,
  score1 INT,
  score2 INT,
  match_date DATE,
  FOREIGN KEY (tournament_id) REFERENCES TOURNAMENT(id),
  FOREIGN KEY (team1_id) REFERENCES TEAM(id),
  FOREIGN KEY (team2_id) REFERENCES TEAM(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
